OpenXiangShan/NEMU

src/isa/riscv64/mmu.c

when access fault and addr misaligned, go on to check if higher priv exception 'pf' will happen
one more thing: when msbs error, raise pf
two more thing: when vm not enable, do not raise pf
three more thing: when mem exception, don't update a/d

rv64: fix bug of excep-priv of ls pf/af/am

---

configs/riscv64-dual-xs-ref_defconfig
include/isa.h
include/memory/paddr.h
src/cpu/difftest/ref.c
src/isa/riscv64/Kconfig
src/isa/riscv64/difftest/ref.c
src/isa/riscv64/system/mmu.c
src/memory/vaddr.c

* `difftest_set_mhartid`
* `difftest_put_gmaddr`
Originally implemented by wakafa

difftest: re-add multi-core difftest APIs

---

src/memory/paddr.c

* It will help to find errors covered by skip in processor difftest

ref: raise exception if access invalid paddr

---

src/cpu/cpu-exec.c
src/isa/riscv64/instr/rva/amo.c
src/isa/riscv64/system/priv.c
src/memory/paddr.c

pmp entry 8-15 used to get wrong host pmpcfg address, which lead to undefined behavior

pmp: fix pmp implementation problems

---

include/rtl/fp.h
include/rtl/rtl.h
lib-include/difftest.h
resource/bbl/Makefile
resource/bbl/bbl.lds
resource/debian/README.md
resource/gcpt_restore/Makefile
resource/gcpt_restore/restore.lds
scripts/build.mk
scripts/config.mk
src/base/output.cpp
src/cpu/difftest/ref.c
src/device/flash.c
src/device/sdcard.c
src/engine/interpreter/c_op.h
src/isa/mips32/system/priv.c
src/isa/riscv32/system/priv.c
src/isa/riscv64/system/mmu.c
src/isa/riscv64/system/priv.c
src/isa/x86/Kconfig
src/isa/x86/instr/logic.h
src/isa/x86/system/priv.c
src/monitor/image_loader.c
src/monitor/ui.c
tools/kconfig/lxdialog/menubox.c
tools/kconfig/lxdialog/util.c
tools/kconfig/preprocess.c

Hi Zihao,
These patches are mainly fixed some typos and check all files
in the project through the spellchecker.

Fix some typos

---

include/cpu/decode.h
include/macro.h

Ported from https://github.com/NJU-ProjectN/nemu/commit/ae8715807dc482db6f6e8f40efc38fcf9d4bc9f4 and https://github.com/NJU-ProjectN/nemu/commit/8417a259398089bb8b590b7785f768c075548d81

cpu,decode: fix the undefined behavior for shifting uint32_t by 32

---

src/isa/riscv64/Kconfig
src/isa/riscv64/local-include/csr.h
src/isa/riscv64/system/mmu.c
src/isa/riscv64/system/priv.c

add pmptable extension as a security enhancement:
* remove original pmpcfg write limit.
* add pmptable check function.

feat(pmptable): add pmptable extension support.

---

src/cpu/cpu-exec.c
src/isa/riscv64/instr/rvv/vcompute.h
src/isa/riscv64/instr/rvv/vcompute_impl.c
src/isa/riscv64/local-include/intr.h
src/isa/riscv64/system/intr.c
src/user/syscall.c

fix vmvxs  and reduciton instr bug
fix msltu msleu msgtu
Added itrace limit to prevent typing too many logs

rv64v: fix rvv vmvxs and reduction

---

src/isa/riscv64/instr/rvv/vcompute.h
src/isa/riscv64/instr/rvv/vcompute_impl.c
src/isa/riscv64/instr/rvv/vldst_impl.c

*fix vfncvt.rod.f.f.w ,vfredusum
*fix vsm.v
Extend the test set with Vector

rv64v: fix fix vfncvt.rod.f.f.w ,vfredusum ,vsm.v

---

src/isa/riscv64/system/priv.c

rv64v: fix mstatus.vs=dirty should set mstatus.sd=1

rv64v: fix mstatus.vs=dirty should set 1

---

src/isa/riscv64/instr/rvv/vreg.h
src/isa/riscv64/system/priv.c

rv64v: fix mstatus-vp of set sd

rv64v: fix mstatus-vp of set sd

---

src/isa/riscv64/instr/rva/amo.c
src/isa/riscv64/instr/special.h

nemu-trap: update when nemu trap sync spike
amo: add amo fault sync

nemu-trap: update when nemu trap sync spikeand sc fault sync

---

src/cpu/cpu-exec.c
src/profiling/profiling_control.c

trace: added ex_name compilation option,fix abs instr count

---

Kconfig
include/cpu/difftest.h
include/debug.h
include/utils.h
src/cpu/cpu-exec.c
src/isa/riscv64/instr/rvf/exec.h
src/utils/log.c

diff: fix fsw mmu and add fpreg diff and disable vstart diff
debug: add watchdog, add trace of csr, fix abs guest_instr
trace: more convenient and small log

rv64：disable vstart diff, add watchdog, fast trace

---

src/cpu/cpu-exec.c
src/isa/riscv64/difftest/dut.c

Adds a comparison of results when floating-point arithmetic is enabled

difftest: add dut frp diff

---

src/isa/riscv64/instr/rvv/vldst_impl.c

fix-rvv: fix vldx-width

---

Kconfig
include/cpu/difftest.h
src/cpu/difftest/dut.c
src/isa/riscv64/difftest/dut.c

add nemu when dut and spike for store diff

difftest: add nemu when dut and spike for store diff

---

.github/workflows/ci.yml

CI: add vectore test

---

Makefile
scripts/build.mk

make 'make clean' could clean softfloat, avoid the '-fpie' flag issue

---

src/isa/riscv64/local-include/intr.h
src/isa/riscv64/system/intr.c
src/isa/riscv64/system/mmu.c

like https://github.com/OpenXiangShan/NEMU/pull/284
Refine the changes to support  on  address misaligned，address fault，load and store page fault

fix: fix vaddr INTR_TVAL on XS_ARCH

---

include/memory/vaddr.h
src/isa/riscv64/include/isa-def.h
src/isa/riscv64/system/mmu.c

when XiangShan forces NEMU to raise a pf and the second stage has guest page fault, NEMU will raise  guest page fault. Because of that, I added a check before NEMU raises gpf. Besides, force_raise_gpf was added.

RVH: fix the bugs about the force_raise_pf and add the force_raise_gpf

---

src/isa/riscv64/system/priv.c

CSR: fix mie mip and mstatus mask

---

include/checkpoint/serializer.h
include/profiling/profiling_control.h
src/checkpoint/serializer.cpp
src/monitor/monitor.c
src/profiling/profiling_control.c

serializer: reserve an interval size of instuctions for warm up

---

src/isa/riscv64/init.c
src/isa/riscv64/local-include/csr.h
src/isa/riscv64/system/priv.c

* Remove custom control CSR bit for Svinval extension, since the extension is ratified.

rv64: fix Svinval extension exception

---

src/isa/riscv64/system/priv.c

* Access fp CSRs will raise EX_II when xstatus.FS=OFF
* Access vec CSRs will raise EX_II when xstatus.VS=OFF

csr: Add access fp/vec CSR check

---

lib-include/difftest.h
src/isa/riscv64/difftest/dut.c
src/isa/riscv64/difftest/ref.c
src/isa/riscv64/include/isa-def.h
src/isa/riscv64/system/priv.c
src/isa/riscv64/system/trigger.c

*difftest support tselect, tdata1 selected, tinfo, tcontrol
*tdata1.data & tdata1.dmode reset to 0
*don't update tdata1.hit

rv64: add trigger csr for difftest

---

src/engine/interpreter/fp.c
src/engine/interpreter/softfloat-fp.h
src/isa/riscv64/instr/fp.c
src/isa/riscv64/instr/rvv/vcompute.h
src/isa/riscv64/instr/rvv/vcompute_impl.c
src/isa/riscv64/instr/rvv/vcompute_impl.h

* when 0 <= rm <= 4, execute inst as usual
* when rm = 5/6, execute inst will raise EX_II
* when rm = 7, rm = frm.data, if rm > 4, execute inst will raise EX_II
* rm = frm.data for vf* inst
*
* inst rely on Spike

csr: add rm permit check

---

src/isa/riscv64/system/mmu.c

For some reason, NEMU lacked logic to raise guest page fault for a/d update in G-Stage address translation. This patch fixes it and adds a/d/u bits check for non-leaf PTEs.
In addition, this patch add checker for n, pbmt & reserved bits just like ptw (VS/S Stage) does.
This patch also improve some code style.

fix(mmu): raise guest page fault for a/d update & n/pbmt/reserved bits 

---

src/isa/riscv64/system/priv.c

This patch check all possible exceptions before read and write and record them, then handle them according to priority.
Previously, NEMU will cause wrong exception trap, handling EX_VI before EX_II be detected.
This patch's approach prevents wrong trp above happening.

fix(csrrw, exception): refactor csr priv check before read and write.

---

src/isa/riscv64/init.c
src/isa/riscv64/local-include/csr.h
src/isa/riscv64/system/intr.c
src/isa/riscv64/system/priv.c

* correct some code format
* fix mnstatus mask as not support zicfilp
* fix m/henvcfg mask according to extension support
* fix sdt was not correctly assigned when trapping to vs/s mode
* fix sdt logic of sret

fix(ss/smdbltrp) : fix xret and dbltrp handling logic, add reg init

---

src/cpu/difftest/ref.c
src/isa/riscv64/difftest/ref.c
src/isa/riscv64/include/isa-def.h
src/isa/riscv64/init.c
src/isa/riscv64/local-include/csr.h
src/isa/riscv64/reg.c
src/isa/riscv64/system/intr.c
src/isa/riscv64/system/priv.c

* menvcfg.stce, henvcfg.stce = 1 when enable sstc extension
* init stimecmp, vstimecmp all of 1s
* fix menvcfg, henvcfg wmask
* get platform interrupts (XiangShan->difftest->NEMU) to diff xip
* add read/write stimecmp in v mode
* refactor xip, xie csr read/write

fix(csr): add support non register interrupt pending and refactor xip/xie csr read/write

---

src/cpu/difftest/ref.c

Add a `difftest_memcpy_init` function. When NEMU is used as a REF for difftest, during the initialization phase, difftest uses `difftest_memcpy_init` to initialize the memory of NEMU, and during the execution phase, `difftest_memcpy` is used for data transfer between NEMU and difftest.
This is because the `difftest_memcpy_init` function uses `nemu_large_memcpy`. This function can effectively reduce physical memory consumption, but it can only guarantee correctness when dest is all 0, so we only use it in the memory initialization phase now. Currently, `difftest_memcpy` uses memcpy to transfer data, which may require more physical memory during simulation, but the correctness can be guaranteed.

fix(diff): use `nemu_large_memcpy` only when init

---

include/macro.h
include/memory/image_loader.h
src/cpu/cpu-exec.c
src/device/io/map.c
src/engine/interpreter/fp.c
src/engine/interpreter/softfloat-fp.h
src/isa/riscv64/instr/decode.c
src/isa/riscv64/instr/fp.c
src/isa/riscv64/instr/rvcbo/exec.h
src/isa/riscv64/instr/rvi/ldst_trig.h
src/isa/riscv64/instr/rvv/vcommon.c
src/isa/riscv64/instr/rvv/vcompute.h
src/isa/riscv64/instr/rvv/vcompute_impl.c
src/isa/riscv64/instr/rvv/vcompute_impl.h
src/isa/riscv64/instr/rvv/vldst_impl.c
src/isa/riscv64/instr/rvv/vreg_impl.c
src/isa/riscv64/system/mmu.c
src/isa/riscv64/system/priv.c
src/isa/riscv64/system/trigger.c
src/memory/paddr.c
src/memory/vaddr.c
src/utils/log.c

- fix initialization of union vars, using  declaration, assignments to define vars, not forced type conversion
- fix initialization of 'bool is_write' crossing 'goto bad', define 'bool is_write' at first
- fix passing to parameter to function, the 'update_global' func take no arguments
- fix some vars type mismatch

fix: fix some potentially problematic code

---

src/memory/paddr.c

Currently, mmio misaligned memory access is checked in paddr read/write process. In this process, the check should based on physical address, because the paddr and vaddr may not match of some requests, such as page table walk. This patch fixes it.

fix(paddr): check mmio misalign based on paddr

---

src/isa/riscv64/system/priv.c

* mip.vssip is alias of hvip.vssip

fix(csr): fix vmode set sip and non vmode get sie

---

lib-include/difftest.h
src/isa/riscv64/difftest/dut.c
src/isa/riscv64/difftest/ref.c
src/isa/riscv64/include/isa-def.h
src/isa/riscv64/local-include/csr.h
src/isa/riscv64/local-include/trigger.h
src/isa/riscv64/reg.c
src/isa/riscv64/system/intr.c
src/isa/riscv64/system/priv.c
src/isa/riscv64/system/trigger.c

This PR should be rebase and merged.

feat(Trigger): Trigger Module support Mcontrol6.

---

src/isa/riscv64/instr/rvc/decode.h

support Zcb load/store instructions: c.lbu, c.lhu, c.lh, c.sb, c.sh

feat(Zcb): support Zcb load/store instructions

---

src/isa/riscv64/system/priv.c

Including mideleg, sstateen0, menvcfg, senvcfg.
And fix write User Level CSRs from VS/VU mode.

fix(csr): fix csr read/write logic.

---

src/cpu/cpu-exec.c
src/isa/riscv64/instr/rvc/decode.h

* move cpu.instr update to set-jmp
* always open RVC exception check

fix(tval): update cpu.instr when set-jmp

---

src/engine/interpreter/fp.c
src/isa/riscv64/instr/rvzfh/exec.h

The src of f16 fsgn is not unbox number

fix(zfh): fix fsgn src unbox

---

configs/riscv64-xs-cpt_defconfig
configs/riscv64-xs-diff-spike_defconfig

* spike commit: 8db172d59681199e332098861691b6082df0c9b2
* spike config: CPU=XIANGSHAN
Including:
* feat: turn on Zimop and Zcmop extensions.
* feat(Zcb): enable Zcb extension.

submodule(ready-to-run): bump spike ref in ready-to-run

---

src/isa/riscv64/difftest/ref.c
src/isa/riscv64/local-include/csr.h
src/isa/riscv64/system/priv.c

* allow write SDT when DTE close
* difftest read xstatus through xstatus_read function

fix(dbltrp): fix difftest read logic of xstatus.SDT

---

Kconfig
include/common.h
include/isa.h
include/utils.h
src/cpu/cpu-exec.c
src/cpu/difftest/ref.c
src/engine/interpreter/rtl-basic.h
src/isa/riscv64/difftest/ref.c
src/isa/riscv64/instr/pseudo.h
src/isa/riscv64/instr/rvc/exec.h
src/isa/riscv64/instr/rvi/control.h
src/memory/Kconfig
src/utils/br_log.c

The previously added br_log is scattered throughout various places. This patch organizes them into a series of functions and places them in one file.

refactor(br_log): organize codes into some functions and one file

---

Makefile
scripts/build.mk

- remove unused -g
- set mtune to native when native build
- remove pie, this makes no sense
- remove optimization flag in build.mk

refactor(makefile): cleanup

---

Makefile
scripts/LibcheckpointAlpha.mk
scripts/config.mk
scripts/repos.mk
src/cpu/difftest/dut.c

fix: split LibcheckpointAlpha build process from menuconfig

---

src/isa/riscv64/difftest/ref.c
src/isa/riscv64/local-include/csr.h
src/isa/riscv64/system/priv.c

* assigin mhpmeventOverflowVec of XiangShan to scountovf.ofvec
* update scountovf.ofvec when write mhpmevent

fix(scountovf): fix reading scountovf & remove writing scountovf

---

scripts/generate_so_for_difftest.sh

Generate diff-so for xiangshan Bitmap

ci:add bitmap diff-so in ci process

---

src/isa/riscv64/instr/rva/amo.c

Because we do not support atomic access for MMIO space, we should check is_in_mmio before real access.

fix(amo): add mmio check for amo/lr/sc instr

---

scripts/Libcheckpoint.mk
scripts/repos.mk

prepare replace LibcheckpointAlpha with LibCheckpoint

feat: add Libcheckpoint repo

---

resource/.gitignore
scripts/Libcheckpoint.mk
scripts/LibcheckpointAlpha.mk
scripts/generate_so_for_difftest.sh
scripts/nanopb.mk
scripts/softfloat.mk

Previous PR #834 did not really resolve this issue. This PR resolves this and abort ci when the scripts reports an error.

fix(ci): resolve missing riscv64-nemu-interpreter-so

---

src/isa/riscv64/system/priv.c

The miselect register implements at least enough bits to support all implemented miselect values.
The siselect register will support the value range 0..0xFFF at a minimum.
The vsiselect register will support the value range 0..0xFFF at a minimum.

fix(xiselect): set the minimum range for xiselect

---

src/isa/riscv64/instr/rvv/vldst_impl.c

In #898 ，we only fix tail element agnostic, this PR we fix mask element agnostic.

fix(vleff): fix mask agnostic when vleff has exception but not raise

---

src/isa/riscv64/instr/rvv/vldst_impl.c

fix(vload): no tail elements when vl <= vstart
