OpenXiangShan/NEMU

- Makefile
- src/device/Kconfig
- src/device/serial.c
- src/device/uartlite.c
This commit adds uartlite as another serial device. The current
default serial device is UART16550. Set CONFIG_SERIAL_UARTLITE
to enable uartlite.
> device,serial: add uartlite support

- Makefile
- src/memory/Kconfig
- src/monitor/monitor.c
This commit adds support for initializing memory with a compressed
gzip file. When CONFIG_MEM_COMPRESS is enabled, files with names
ending with ".gz" will be seen as compressed gzip files and be
decompressed before loading into memory.
Only non-zero bytes are copied into pmem, to avoid using too much
memory (by copy-on-write).
> monitor: support init mem with a gz file

- src/cpu/cpu-exec.c
- src/monitor/monitor.c
- src/monitor/ui.c
This commit adds support to specify the max number of instructions
executed. Use --max-instr or -I to pass this argument to nemu.
> monitor,ui: add max-instr argument to cmd_c and main functions

- Kconfig
- configs/riscv64-xs-ref_defconfig
- src/isa/riscv64/instr/fp.c
- src/isa/riscv64/system/priv.c
* Fix fflags implementation, previous fflag should not be cleared by `isa_fp_set_ex`
* Add panic on unimplemented CSR config
> rv64: let fflags be accrued, add panic on unimplemented CSR config

- configs/riscv64-xs_defconfig
We detect misaligned memory accessing by software to deal with that
in Linux. Now riscv64-xs_defconfig should be able to boot up Linux.
> Detect misalign mem access by software for XiangShan

- Kconfig
Every bits should be copy from dut. Otherwise, uninitialized ref memory would be random values, which leads to random results when launching difftest.
> Fix bug in function nemu_large_memcpy.

- include/memory/paddr.h
- src/isa/riscv32/system/mmu.c
- src/isa/riscv64/local-include/intr.h
- src/isa/riscv64/system/intr.c
- src/isa/riscv64/system/mmu.c
- src/isa/x86/system/mmu.c
- src/memory/host-tlb.c
- src/memory/paddr.c
- src/memory/vaddr.c
On trap into M-mode, mtval should be updated. Otherwise, stval is updated.
> intr: fix mtval and stval update condition

- src/isa/riscv64/difftest/ref.c
LR address is unnecessary to force sc to fail. Copying LR address
makes NEMU fails even when lr_valid is true, because the address
may not be correct.
> ref: don't copy lr address from dut

- src/monitor/monitor.c
fix assertion fault when no output path provided, mentioned in https://github.com/OpenXiangShan/NEMU/issues/62
> gcpt: skip unnecessary inits when cpt related features are disabled

- Kconfig
- src/cpu/cpu-exec.c
* Fix debug inst trace format to disasm inst correctlly
c_beqz  s0,0x80001        // before fix
c_beqz  s0,0x80001ac0  // fixed
* Now it is possible to enable DEBUG config to print inst trace
(pc, inst, dasm) in co-simulation. It should be helpful when we
only have basic diff.
> debug: fix inst trace format, enable trace for co-sim

- src/isa/riscv64/instr/rvb/exec.h
`shamt` field for B-extension `slli.uw` instruction is 6 bits wide, as specified in [RISC-V Bit-Manipulation ISA-extensions version 1.0.0](https://github.com/riscv/riscv-bitmanip/releases/download/1.0.0/bitmanip-1.0.0-38-g865e7a7.pdf), page 52.
> riscv64: fix imm width of B-ext slli.uw

- src/isa/riscv64/include/isa-all-instr.h
- src/isa/riscv64/instr/decode.c
- src/isa/riscv64/instr/priv/exec.h
- src/isa/riscv64/system/intr.c
- src/isa/riscv64/system/priv.c
This PR fix several bugs of H extention and performance optimization.
* Fix compile error when enabling "Enable debug features: instruction tracing and watchpoint" (`CONFIG_DEBUG`)
* Duplicated definition of ebreak caused this problem
* Fix the issue of EBREAK instruction causing segmentation fault when enabling "Performance optimization" (`CONFIG_PERF_OPT`) #132 
* EBREAK was missed during decoding Type-I instruction, causing pointer `tnext` of its `Decode` struct to be NULL.
* Fix executing incorrect VS-mode instructions in M-mode.
* Some VS-mode instructions and M-mode instructions have the same PC address. NEMU did not flush TCACHE when an exception which changing virtualization mode occurs. Fix it.
这个合并请求修复了 H 扩展和性能优化相关的若干问题。
* 修复了启用“Enable debug features: instruction tracing and …
> RV64: fix several bugs of H extention and performance optimization

- include/utils.h
- src/checkpoint/simpoint.cpp
- src/cpu/cpu-exec.c
- src/monitor/monitor.c
- src/utils/log.c
modify command line parameter
-l: output all log to a file with unlimited size, so the file maybe 10G or 100G.
--small-file: output log to a file with limited size when nemu end the program instead of "ctrl + c", the log in the file is always information near the end of the program. For example, when difftest find a bug, small log will save some log that output before executing the error instruction, instead of save all log from the start of program to the end.
> add a command line parameter: --small-log, output log to a limited size FILE, but log is always up to date

- src/memory/host-tlb.c
fix permission check bug:
- add hostxtlb, separate mem read and ifetch
- put the paddr_read or paddr_write before the tlb record
- no performance loss
other fixs:
- change MODE_S to cpu.mode
- change MEM_TYPE_READ to type
- remove isa_mmu_check in va2pa
> fix(host-tlb.c): hosttlb permission check bug and some other bugs

- src/isa/riscv64/instr/rva/amo.c
According to the RISC-V spec, regardless of success or failure, executing an SC.W/D instruction invalidates any reservation held by this hart.
> rv64,amo: SC should invalidate any reservation set

- configs/riscv64-nutshell-ref_defconfig
- configs/riscv64-xs-ref_defconfig
Link-time optimizations may not work with clang sanitizer.
> configs: disable LTO for ref configs

- src/cpu/cpu-exec.c
This would avoid previous instructions' cpu.amo affecting the following instructions.
However, trace cache may not be affected and may have bugs.
> exec: reset cpu.amo before executing instructions

- src/isa/riscv64/system/mmu.c
According to the RISC-V spec, reserved bits in the page table entry must be zeroed by software, or else a page-fault exception is raised.
> mmu: check pte.pad during the ptw

- src/memory/paddr.c
Note: we are using MAP_FIXED here, in the SHARED mode, even if init_mem may be called multiple times, the memory space will be allocated only once at the first time called.
See https://man7.org/linux/man-pages/man2/mmap.2.html for details.
> paddr: add comments to mmap in init_mem

- src/isa/riscv64/system/mmu.c
This will cause false positives in co-simulation because NEMU does not have the same peripherals as the DUT.
> mmu: do not allow MMIO PTEs in SHARE mode

- src/checkpoint/simpoint.cpp
No need to initialize the simpoint bbv files before calling init.
> checkpoint: avoid simpoint files before init

- src/cpu/difftest/ref.c
- src/device/device.c
- src/device/flash.c
flash_init should be called after load_flash_contents, which init the space pointer.
> device: fix the init steps of flash

- src/isa/riscv64/system/priv.c
Hello, during the simulation process, I noticed that the 0th and 4th bits of mstatus in NEMU are not aligned with the requirements in the privilege specification. These positions need to be cleared to zero.
> rv64,priv: fix the write mask of mstatus

- src/isa/riscv64/instr/rvv/vcfg.h
- src/isa/riscv64/instr/rvv/vcommon.c
- src/isa/riscv64/instr/rvv/vcommon.h
This commit fix the situation that a vset{i}vl{i} instruction have illegal vlmul and vsew should set vl and rd to zero。
> fix,vset{i}vl{i}:vlmul and vsew is illegal, set vl and rd zero

- src/isa/riscv64/instr/rvv/vcompute.h
- src/isa/riscv64/instr/rvv/vcompute_impl.c
fix vfwredusum, vfwredosum, vsaddu, vslidedown, vmsbf, vfmvfms, vfirst
> rv64v: fix some vector extension instruction

- include/cpu/decode.h
- src/isa/riscv64/instr/rvv/vldst_impl.c
- src/isa/riscv64/system/mmu.c
- src/memory/vaddr.c
skip the alignment check for out-of-order Vector access add an access alignment check add more mmu debuglog
> rv64v: add access alignment check and skip the alignment check

- src/isa/riscv64/include/isa-def.h
> rv64v: remove vamo

- src/isa/riscv64/difftest/dut.c
Prevent the spike from repeatedly triggering the time interrupt
> interrupt: shield spike mtip stip utip

- src/isa/riscv64/system/priv.c
The function `csr_read()` lacks a mask for vsstatus, resulting in the reading of non-zero values from reserved WPRI fields. 
Actually `csr_write()` includes a mask for vsstatus, but incorrect values are being received from the Difftest DUT during initialization.
> RVH: fix read mask absence of vsstatus

- include/cpu/difftest.h
- include/memory/paddr.h
- src/memory/paddr.c
Fixed the case that store diff does not diff enough times under V vector memory access
> vector-diff: vector store not diff enough times

- Kconfig
- include/memory/paddr.h
- src/memory/paddr.c
- src/monitor/monitor.c
- src/monitor/ui.c
When MEMORY_REGION_ANALYSISis configured, the program's memory segment usage analysis is started and printed or exported to a file. The path is set using --mem_use_record_file, and the analysis is performed in 32MB block units by default
> profile: add program memory segment usage analysis

- src/memory/Kconfig
Changed the ability to load gz when difftest is enabled
> kconfig: fix no MEM_COMPRESS chose

- Makefile
- src/cpu/cpu-exec.c
- src/engine/interpreter/rtl-basic.h
When compiling as ref, you don't need to enable checkpoint functionality, which saves you 50kb of compile size and avoids some cases where the host doesn't have the relevant library files to run
在作为ref编译时不需要开启checkpoint的相关功能，这样可以减少50kb的编译大小，并且避免一些因为宿主机没有相关库文件造成无法运行的情况
> ref: remove unnecessary compilation links

- src/isa/riscv64/system/mmu.c
In xiangshan, the virtual address is trimmed to save the chip area. When SAM LAM exception is triggered, only the address with a large size of 39 bits will be written, so certain changes need to be made when xs ref is used
> fix: fix sv39 mtval

- include/rtl/fp.h
- src/engine/interpreter/fp.c
- src/isa/riscv64/instr/rvv/vcompute.h
- src/isa/riscv64/instr/rvv/vcompute_impl.c
- src/isa/riscv64/instr/rvv/vldst_impl.c
1. fix align bug in the set_vreg of vld. Align is based on eew and emul, not just sew and lmul.
2. fix a bug in the vmsbf.  It generated redundant assign for the rule 'when there are no active 1 in the source, set all active elements in the destination to 1'. This rule was already ensured by the for loop, and this way would overwrite non-active elements in destnation.
3. for f16_to_i8 vfncvt, add  processing path for it.
4. for i8_to_f16 vfwcvt, add processing path for it, and delete redundant convert assign in i16_to_f32 and i32_to_f64.
> rv64v: fix four bugs discovered by riscv-vector-intrinsic-fuzzing

- src/isa/riscv64/instr/rvv/vldst_impl.c
First, in vldx and vstx, v_width is not determine by vtype->sew, so I reassign v_width the real value from s->isa.instr.vldfp.v_width, and assign index_width by different v_width value defined in spec.
Second, assign for s->v_width will cause errors when turn on perf_opt because it change the value may be used in later instructions.
> rv64v: fix bugs in vldx and vstx when turn on perf_opt

- src/isa/riscv64/init.c
mstatus.vs can not be zero when vector extension is present.
> rv64v: fix an assignment bug in mstatus.vs.

- resource/bbl/src/encoding.h
According to riscv spec, I reorganized the fields in mstatus and sstatus.
> csr: fix some field mask error in mstatus and sstatus.

- src/isa/riscv64/system/priv.c
There is two bugs in this code:
* If `!srnctl->svinval`, sinval.vma would throw a Virtual Instruction exception. It should throw an Illegal Instruction exception instead.
* If exec sinval.vma in U-mode, it would not throw an exception. It should throw a Illegal Instruction exception instead.
> priv: fix wrong behavior of sinval.vma

- src/isa/riscv64/system/priv.c
When enabling H-ext, NEMU uses a incorrect write mask to CSR medeleg. This write mask lacks of some lower bits. This PR Fix it.
> CSR: fix wrong wmask of medeleg of H-ext

- src/isa/riscv64/system/priv.c
> CSR: fix the mstatus's writing mask when RVH and RVV extensions are opened

- include/memory/paddr.h
- src/cpu/difftest/ref.c
- src/memory/Kconfig
- src/memory/paddr.c
When restoring from checkpoints, most memory contents of DUT and reference are the same. Therefore, creating a COW mirror memory in DUT side as the memory of reference design can save memory, especially when using multi-core difftest.
> memory: Allow DUT to provide pmem for NEMU ref

- include/memory/paddr.h
- src/cpu/difftest/ref.c
- src/memory/paddr.c
Previous we use MAP_FIXED for single-core, prevent allocating memory repeatedly for each initialization.
For dual-core, we also want to use mmap for MEMORY_SIZE config. To avoid different core conflict with same PMEM_BASE, we apply different pmem_base according to hartid.
> memory: mmap difftest pmem_base for dual-core difftest

- src/isa/riscv64/clint.c
修改非 CONFIG_DETERMINISTIC 情况下 mtime计算方法
mtime = 运行时间(微秒) / 每周期微秒数
CLOCK_FREQ 设置为 1000000ul 与 opensbi 中 system.dts 对齐
> clint: use physical uptime for real-time timer

- src/isa/riscv64/system/mmu.c
Address misaligned exceptions may frequently happen. We should avoid too many logs.
> mmu: use Logm for addr alignment checker

- src/isa/riscv64/difftest/ref.c
- src/isa/riscv64/local-include/csr.h
- src/isa/riscv64/system/priv.c
sstatus is a masked register of mstatus. Its read and write masks are partial masks of the mstatus masks.
This commit fixes the wmask for sstatus.fs, which should depend on the existence of FPU. We also clean up some duplicated code.
> csr: fix the read/write masks of sstatus

- src/isa/riscv64/local-include/csr.h
- src/isa/riscv64/system/priv.c
As more and more extentions of RISC-V have been added into NEMU, the CSR part becomes completely unreadable and unmaintainable. This patch aims to enhance readability & maintainability.
In this patch, the order of CSRs and the name of each CSR part follows the RISC-V privileged ISA. All CSR mappings merge into one mapping marco "CSRS". The form of switches, which control CSR existence by specific extension, are unifed.
This patch add these CSRs according to ISA: cycle, time, instret, hpmcounter3~31, senvcfg, scountinhibit, hcontext, mconfigptr, mscontext. These CSRs are still lack of functionality, and they may not be actually existed due to lack of according CONFIG defines. Also, fix wrong name of CSR time (0xC01).
This patch is part of a series aimed at enhancing the functionality, …
> csr: rewrite csr.h to improve readability & maintainability

- src/isa/riscv64/Kconfig
- src/isa/riscv64/local-include/csr.h
- src/isa/riscv64/system/priv.c
Float point CSRs should not exist when there is no FPU (no RVF / RVD support).
This patch wraps mapping and structure of fp CSRs in CONFIG_FPU_NONE and adjusts csr_read() & csr_write() function accordingly.
This patch also add dependency of CONFIG_RVV on !FPU_NONE, which is required by RISC-V unpriv isa.
> csr, float: wrap fp CSRs in CONFIG_FPU_NONE

- src/isa/riscv64/instr/rvv/vcommon.c
- src/isa/riscv64/instr/rvv/vcommon.h
- src/isa/riscv64/instr/rvv/vcompute.h
- src/isa/riscv64/instr/rvv/vcompute_impl.c
For fp 16/32 obtained from a 64-bit number, if the upper bits are not all 1s, it is considered a CNAN. In this case, the lower significant bits need to be set to the corresponding NAN.
> rv64v: fix a bug that no boxing for fp in f2v case.

- src/isa/riscv64/difftest/ref.c
- src/isa/riscv64/init.c
- src/isa/riscv64/instr/fp.c
- src/isa/riscv64/instr/vp.c
- src/isa/riscv64/local-include/csr.h
- src/isa/riscv64/reg.c
- src/isa/riscv64/system/priv.c
* Set vs and fs of mstatus to OFF(0) when initial hart state.
* Set vstatus.vs dirty when in virtual mode and modifying vector status.
* As specified in RISC-V spec, the mstatus.SD is read-only field and producted from FS, VS or XS is dirty.
* Produce SD field when SD field when copy from REF to DIFFTEST.
* Hardwire SD to 0 when copy from DIFFTEST to REF.
> Fix FS,VS and SD fields in mstatus and vsstatus

- src/isa/riscv64/instr/rvv/vcompute.h
- src/isa/riscv64/instr/rvv/vcompute_impl.c
* remove aligned check for vfmvfs and vfmvsf
* replace assert with long jump exception for vector float instructions
* add vm check for the vmask instructions
* add src and vm check for the vmv instructions
> rv64v: fix and add some exception check for vector instructions

- src/isa/riscv64/instr/rvv/vcompute_impl.c
- src/isa/riscv64/instr/rvv/vldst.h
* vset{i}vl{i} and whole register loads and stores do not depend upon vtype
> rv64v: fix vill check for vector instructions

- src/isa/riscv64/instr/rvf/decode.h
- src/isa/riscv64/instr/rvv/vcfg.h
- src/isa/riscv64/instr/rvv/vcommon.c
- src/isa/riscv64/instr/rvv/vcommon.h
- src/isa/riscv64/instr/rvv/vcompute.h
- src/isa/riscv64/instr/rvv/vcompute_impl.c
- src/isa/riscv64/instr/rvv/vldst.h
- src/isa/riscv64/instr/rvv/vldst_impl.c
- src/isa/riscv64/instr/rvv/vreg_impl.c
- src/isa/riscv64/system/priv.c
* add exception check for vector load/store, remove alignment check when access vector registers
* move vector load/store instructions info generation from decode stage to execute stage
* fix illegal vtype check
* when vstart is not zero and is a arithmetic vector instruction, raise illegal instruction exception
* support sew check for zext and sext instructions
> rv64v: fix some exception checks with bugs or missing

- src/checkpoint/serializer.cpp
- src/monitor/monitor.c
- Previously, checkpointing always requires user to provide a gcpt restorer. This is not necessary when we provide an all-in-one image containing gcpt restorer + bootloader + kernel
> checkpoint: allow to provide an all-in-one workload without restorer

- src/isa/riscv64/instr/rvv/vreg_impl.c
* when lmul == 4, the vill will be setted to 1, if vill is 1, running vector instructions which depend on vtype will raise exception
> rv64v: remove panic when lmul is reserved value

- src/isa/riscv64/reg.c
Fix a bug that the correct **xstatus** value could not be obtained when executing **info r** command. This was because the code only assigned a value to **xstatus->val** when **xstatus** should change, but did not update the value of **cpu.xstatus**. One feasible method is to assign values to both **xstatus->val** and update **cpu.xstatus** every time **xstatus** changes. However, I think this approach is too cumbersome, requiring changes to many parts of the code. Therefore, I chose to generate the value of **cpu.xstatus** from **xstatus->val** whenever **cpu.xstatus** is needed. So why didn't I just add a copy of **xstatus** but instead executed the entire **csr_prepare** function? This is to facilitate potential future issues such as the **sd** field in **xstatus** is read-only. In …
> csr: update and display the correct cpu.xstatus value.

- src/cpu/difftest/dut.c
- When trapping on exception, occasionally, NEMU has executed
`csrrw   tp,mscratch,tp`, but Spike has not.
After advancing Spike for one more step,
Spike's architectural state will match with NEMU again.
> difftest-as-dut: allow ref model to advance one more step on mismatch

- src/cpu/difftest/dut.c
- src/isa/riscv64/system/intr.c
When there is an exception happen in nemu as dut, spike should also execute the same instruction that caused the exception.
In particular, the **ebreak** and **ecall** instructions are different from other instructions that can cause exceptions, because when they are executed in nemu, spike has already been instructed to execute the corresponding **ebreak** and **ecall** instructions, so there is no need to guide spike to execute another instruction in either case.
> difftest: guide spike to exec the instruction cause an exception.

- .github/workflows/ci.yml
- .gitignore
- scripts/Dockerfile
- scripts/generate_so_for_difftest.sh
- scripts/generate_so_from_docker.sh
This PR add a CI to compile difftest-so in CentOS 7 docker and upload them as an archived artifact. Users can obtain them through Actions page, like https://github.com/OpenXiangShan/NEMU/actions/runs/10185291877.
> ci: build difftest so in docker

- src/isa/riscv64/local-include/csr.h
- src/isa/riscv64/system/priv.c
* This commit modify the strategy of WARL of xtvec.mode
* At present, only spike uses write mask to handle the illegal value of xtvec.mode. In this strategy, when write mtvec.mode with illegal value 0b11, spike will always store legal value 0b01(Vectored) in mtvec.mode.
* sail-riscv and qemu uses "keep old value" strategy to handle the illegal write value. When write mtvec.mode with illegal value 0b11 or 0b10, sail-riscv and qemu will always keep the old value in mtvec.mode which must be legal value.
> csr: use "keep old value" strategy to implement WARL of xtvec.mode

- src/isa/riscv64/instr/rvv/vldst_impl.c
Vector index store should not checked for overlap.
> rv64v: fix vector index store check.

- scripts/build.mk
- PGO improves simulation speed on some benchmarks. For example, it speeds up vectorized h264_sss by ~10%
> build: add PGO for NEMU

- include/cpu/decode.h
- include/memory/host.h
- scripts/build.mk
- src/cpu/cpu-exec.c
- src/isa/riscv64/instr/rvv/vcompute.h
- src/isa/riscv64/instr/rvv/vcompute_impl.c
- src/isa/riscv64/instr/rvv/vldst_impl.c
- src/isa/riscv64/instr/rvv/vreg.h
- src/isa/riscv64/instr/rvv/vreg_impl.c
- src/isa/riscv64/local-include/csr.h
- src/memory/host-tlb.c
- src/memory/paddr.c
- src/memory/vaddr.c
- Remove useless parameters for get_mask, which is misleading
- For unit-stride ld/st, perform a dummy memory access to obtain host addr. If host TLB miss or crossing page, then we fall back to the slow path. This avoids redundant address translation.
- Implement masked ld/st with bit operations instread of branches, which makes code easier to vectorize
- Always prefer bounded loop to make it easier to vectorize
- Add optimization flags: -flto -ftree-vectorize -march=native
- Allow to check fast vse with slow path and store commit difftest
- This patch improves the simualtion speed of vectorized h264_sss by 3x, improves the simualtion speed of early 2G instructions of vectorized h264_sss by 9x.
> rv64v: fast path for unit-stride ld/st; vectorize this fast path

- src/memory/vaddr.c
Because when NEMU is running alone and virtual-to-physical address translation is not enabled, if an unaligned memory access occurs, the unaligned exception will not be reported, resulting in inconsistencies with spike's diff.
> vaddr: always check misalign in vaddr_read/write

- .github/workflows/ci.yml
As the bug was solved in PR #454, this patch enable crypto test in CI.
> ci: enable crypto test

- src/isa/riscv64/system/mmu.c
According to RISC-V priv spec, only leaf PTE could have A/D/U bits. Otherwise, hardware would raises PF. This previous NEMU did not handle this.
This patch also fixes the incorrect check for reserved pads in PTE.
> fix(mmu): raise PF if A/D/U bits of an non-leaf PTE is set

- src/isa/riscv64/system/intr.c
- src/isa/riscv64/system/mmu.c
This PR fixes two problems:
- mtval2 is not clear properly in breakpoint exception.
- GPF exception is not raised properly for misaligned G-stage superpage.
See commit message for details.
Please use rebase to merge this PR.
> fix: correct exception behaviour for misaligned superpage (GPF) & mtval (BP)

- src/cpu/cpu-exec.c
NEMU updates cpu.instr every instruction only if PERF_OPT is disabled, so that *tval could not get proper instuction info in PERF_OPT mode. This patch update cpu.instr in update_global() function, so that cpu.instr could be udpated properly without performance degradation.
> fix(cpu-exec): capture instr for mtval in perf_opt

- src/engine/interpreter/hostcall.c
treat invalid instr as illegal instr and do not report it when CONFIG_REPORT_ILLEGAL_INSTR undefined.
> feat(EX_II): when as DUT, raise EX_II if `CONFIG_REPORT_ILLEGAL_INSTR` not set

- include/memory/paddr.h
- src/isa/riscv64/instr/rvv/vldst_impl.c
- src/memory/paddr.c
- src/memory/vaddr.c
* the priority of misalign is higher than access fault when access mmio
* fix some log and printf, not display them in default config
> fix(mmu): still raise misalign exception when access mmio

- src/isa/riscv64/instr/rvv/vldst_impl.c
`__attribute_maybe_unused__` is a feature from c++17 standard, which causes compilation error in gcc-9 (Ubuntu 20.04). Also, `__attribute__((unused))` is the one which could be used in C.
> fix(rvv): compilation error caused by c++17 feature

- src/isa/riscv64/system/priv.c
VU mode access S mode csr should also rasie EX_VI.
> fix(exception): fix priv check for csr access.

- src/isa/riscv64/system/priv.c
Because EX_II prior to EX_VI, we can hanle EX_II immediately when EX_II is detected.
And EX_VI is stored until EX_II is not detected after execute whole priv check code.
> refactor(exception): When EX_II is detected, handle it immediately.

- include/memory/paddr.h
- src/checkpoint/serializer.cpp
- src/isa/riscv64/system/mmu.c
- src/memory/host-tlb.c
- src/memory/paddr.c
- src/memory/vaddr.c
In riscv-privileged, it is load or store in G-stage which support VS-stage, such as to get the non-leaf pte of VS-stage
> For G-stage address translation, all memory accesses (including those made to access data structures for VS-stage address translation) are considered to be user-level accesses, as though executed in U-mode. Access type permissions—readable, writable, or executable—are checked during G-stage translation the same as for VS-stage translation. For a memory access made to support VS-stage address translation (such as to read/write a VS-level page table), permissions and the need to set A and/or D bits at the G-stage level are checked as though for an implicit load or store, not for the original access type. However, any exception is always reported for the original access …
> fix(mmu, RVH): s2xlate which support VS-stage is load rather than original access type

- Kconfig
- configs/riscv64-dual-xs-ref_defconfig
- configs/riscv64-xs-cpt_defconfig
- configs/riscv64-xs-diff-spike_defconfig
- configs/riscv64-xs-ref_defconfig
- configs/riscv64-xs_defconfig
- src/isa/riscv64/system/mmu.c
This PR bumps the spike in ready-to-run and spike changes a lot. One important change is enabling misaligned memory access for XiangShan. So this PR does something on config. See commit message for details.
> fix: bump spike in ready-to-run and align misaligned issue

- src/isa/riscv64/system/mmu.c
If ppn is greater than 32 bits and ppn moves to the left, the high bit will disapear. Need to turn ppn into the uint64 first.
> fix(mmu, RVH): fix the bug that ppn moves to the left and the high bit disappears

- src/isa/riscv64/system/intr.c
- src/isa/riscv64/system/mmu.c
According to RISC-V priv spec, mtinst/htinst could be always written zero on trap into M/HS-mode, except for Guest-Page-Fault traps that meet both of the following conditions:
- the trap is caused by a G-stage translation which supports VS-stage translation
- a nonzero value is written to mtval2/htval
Unfortunately, XiangShan/NEMU meets both of conditions.
This patch adds support for writing proper value to mtinst/htinst when specific trap occurs. This patch also bump Spike in ready-to-run to align this.
> feat(trap): support m/htinst for specific G-stage translation

- include/cpu/decode.h
- include/cpu/ifetch.h
- include/utils.h
- src/checkpoint/path_manager.cpp
- src/checkpoint/serializer.cpp
- src/checkpoint/simpoint.cpp
- src/cpu/cpu-exec.c
- src/memory/paddr.c
- src/monitor/monitor.c
- src/utils/log.c
When snprintf dest buffer is a static array with fixed length, and src
also a static array with fixed length, compiler will tell if there will
be a write truncation and warn about it. This commit could fix this warn.
The logic for outputting the log to a file was a bit hard to understand,
refactored this part of the code.
> fix(snprintf),refactor(small/fast log): fix truncated writing warning, refactor output to log file

- src/isa/riscv64/local-include/intr.h
- src/isa/riscv64/system/intr.c
- src/isa/riscv64/system/mmu.c
- src/memory/paddr.c
Commit https://github.com/OpenXiangShan/NEMU/commit/2cca2bafa90b9f6221158f01e535be0930323c75 truncates value writing to *tval from 64-bit to 48-bit, thus adapting to RTL.
This reverts commit https://github.com/OpenXiangShan/NEMU/commit/2cca2bafa90b9f6221158f01e535be0930323c75 as RTL can save high address bits to *val
> feat(exception): Write full vaddr to *tval

- include/memory/paddr.h
- src/cpu/cpu-exec.c
- src/cpu/difftest/ref.c
- src/memory/paddr.c
To make the store event information more efficient, we now add 'pc' to the store event. The changes need to be used with the new difftest changes.
> feat(store_event): add 'pc' output for store event check

- include/memory/paddr.h
- src/cpu/difftest/ref.c
- src/memory/paddr.c
Temporarily revert destructive changes to the store event api check.
Add pc and robidx output of store events for difftest and rtl using other means.
> fix(store_event): revert destructive changes to the store event  check api

- src/isa/riscv64/init.c
- src/isa/riscv64/local-include/csr.h
- src/isa/riscv64/system/priv.c
This PR initializes the xenvcfg.cbo bits and fix xenvcfg wmask.
Add senvcfg csr read/write.
MeanWhile, when xenvcfg.CBIE = 2 is reserved and cannot be written.
Bump ready-to-run to support CBO extension.
> fix(cbo): bump ready-to-run to support CBO extension and fix xenvcfg

- src/isa/riscv64/clint.c
- src/isa/riscv64/system/priv.c
* When Diff between XiangShan and NEMU, the time interrupt signal comes from XiangShan
* When NEMU is running alone, the time interrupt signal can be generated by itself
> fix(sstc): fix time interrupt

- src/checkpoint/serializer.cpp
since nix saves simpoints0 file with r--, however fstream asserts file with rw-, overwise get Permission denied error, write permission is useless.
> serializer fstream only need read permission

- src/isa/riscv64/instr/decode.c
- src/isa/riscv64/instr/rvi/ldst_trig.h
- src/isa/riscv64/instr/rvv/vldst_impl.c
- src/isa/riscv64/local-include/trigger.h
- src/isa/riscv64/system/intr.c
- src/isa/riscv64/system/trigger.c
* Support vector load/store trigger.
* Fix trap value when BreakPoint exception occurs. When a breakpoint exception occurs on an instruction fetch, load, or store,
then mtval will contain the faulting virtual address.
> Support vector ld/st trigger.

- src/isa/riscv64/instr/decode.c
After fetch and decode, the s->snpc is the sequential next pc.
However, the vaddr for after fetch trigger should be the current pc.
> fix(trigger): fix PC vaddr for instruction fetch trigger.

- include/isa.h
- src/cpu/difftest/ref.c
- src/isa/riscv64/difftest/ref.c
- src/isa/riscv64/local-include/csr.h
lcofi is reg-interrupt-pending, which needs to write to mip reg
> fix(mip): fix rtl guidance for mip.lcofi logic

- src/isa/riscv64/system/priv.c
This reverts commit ffe101a53d5479253377eb662b0012426c61290e.
when access vstimecmp in vs-mode with menvcfg.STCE==0 || mcounteren.TM==0 , raise EX_II instead of EX_VI
> Revert "fix(priv): do not check xstimecmp if normal permit is violated (#571)"

- src/memory/paddr.c
Although function raise_read_access_fault is named "read", it is used widely for any kind of access fault. A call with type = `MEM_TYPE_WRITE` raises LAF rather than SAF. This patch fixes this.
> fix(paddr): raise SAF if type is MEM_TYPE_WRITE

- src/isa/riscv64/instr/rvd/exec.h
- src/isa/riscv64/instr/rvf/exec.h
- src/isa/riscv64/instr/rvzfa/exec.h
- src/isa/riscv64/instr/rvzfh/exec.h
Accroding to manual, either to set or not to set xstatus.fs when no fp exception is raised is ok. To align with XS, we change the behavior of NEMU.
> fix(fp): set xstatus.fs unconditionally on fp comparision

- src/memory/vaddr.c
In our design, requests that cross page are split into two non-cross page requests in `vaddr_write_cross_page`, which are handled separately in `vaddr_trans_and_check_exception`.
However, in previous design, `vaddr_trans_and_check_exception` would pass a page-aligned vaddr (`vaddr & ~PAGE_MASK`) into `isa_mmu_translate`, which would result in the lower 12 bits of exception address (page offset) written to *tval going to all zeros. This will result in an error against rtl if an exception occurs. This commit fixes it.
> Fix(vaddr): cross page write check should use original vaddr

- include/cpu/cpu.h
- src/cpu/cpu-exec.c
- src/cpu/difftest/dut.c
- src/cpu/tcache.c
- src/isa/mips32/instr/special.h
- src/isa/mips32/system/mmu.c
- src/isa/riscv32/instr/special.h
- src/isa/riscv64/instr/priv/system.c
- src/isa/riscv64/instr/rvc/exec.h
- src/isa/riscv64/instr/rvv/vldst_impl.c
- src/isa/riscv64/instr/special.h
- src/isa/x86/instr/special.h
- src/user/syscall.c
* Use a env stack to record context saved by setjmp, and longjmp to corresponding context pointed by a context index.
* Refactor vector Unit-stride Fault-Only-First Loads by using context stack above.
> refactor vector Unit-stride Fault-Only-First Loads.

- src/isa/riscv64/instr/rvd/exec.h
- src/isa/riscv64/instr/rvf/exec.h
- src/isa/riscv64/instr/rvv/vcompute.h
- src/isa/riscv64/instr/rvv/vcompute_impl.c
- src/isa/riscv64/instr/rvzfa/exec.h
- src/isa/riscv64/instr/rvzfh/exec.h
This commit also fixes a bug where fs and vs are not set to dirty when `check_vstart_ignore(s)` returns 1.
> fix(fcvt): set xstatus.fs unconditionally on fcvt

- Kconfig
- configs/riscv64-dual-xs-ref_defconfig
- configs/riscv64-xs-cpt_defconfig
- configs/riscv64-xs-diff-spike_defconfig
- configs/riscv64-xs-ref_defconfig
- configs/riscv64-xs_defconfig
- src/isa/riscv64/instr/rva/amo.c
- src/isa/riscv64/system/mmu.c
- src/memory/paddr.c
Since Xiangshan atomic instructions do not support hardware misaligned memory access, so if nemu finds that the addresses are misaligned before executing the atomic instructions, directly reports an exception to make the behavior of both sides consistent.
> fix(amo-diff): report misalign exception in amo instruction

- src/isa/riscv64/local-include/intr.h
- src/isa/riscv64/system/mmu.c
When delegating PF to VS, it should update vstval; when delegating PF to S, it should update stval; otherwise, it should update mtval. However, the previous NEMU sometimes updates vstval when delegating PF to VS. It's really strange that we did not find this bug brefore.
This patch also adds INTR_TVAL2_REG / INTR_TINST_REG macro and uses them to refractor some other codes.
> fix(mmu): incorrect tval update when delegating to VS

- include/rtl/pseudo.h
- src/cpu/difftest/dut.c
- src/device/audio.c
- src/device/disk.c
- src/device/intr.c
- src/device/vga.c
- src/memory/vaddr.c
- src/monitor/ui.c
- src/monitor/watchpoint.c
- src/utils/expr.c
- tools/gen-expr/gen-expr.c
The __ICS_EXPORT macro is used to generate the code framework for ICS course of NJU. Since the OpenXiangShan/NEMU no longer undertakes this task, this macro could be removed.
This patch only removed the __ICS_EXPORT in public and riscv64 codes, because riscv32, mips and x86 are excepted to be deprecated in the feature.
> refactor: remove the macro __ICS_EXPORT

- include/isa.h
- src/cpu/difftest/ref.c
- src/isa/riscv64/difftest/ref.c
- src/isa/riscv64/include/isa-def.h
- src/isa/riscv64/local-include/csr.h
- src/isa/riscv64/system/priv.c
this pr include:
fix(mhpmevent): add CSRS_M_HPMEVENTS_STRUCT for mhpmevent csr.
fix(mhpmevent): add rtl guidance for mhpmevent.of logic
fix(csrrw): add legal write check for mstatus.mpp, mnstatus.mnpp, hpmevent.optype and wmask for mhpmevent
> fix(mhpmevent): add struct, rtl guidance and legal check for mhpmevent csr

- src/cpu/cpu-exec.c
- src/isa/riscv64/Kconfig
- src/isa/riscv64/init.c
- src/isa/riscv64/instr/decode.c
- src/isa/riscv64/system/intr.c
- src/isa/riscv64/system/mmu.c
- src/isa/riscv64/system/priv.c
* remove redundant assign code
* adjust some MUXDEF to IFDEF
* add NMIE_INIT config depend on CONFIG_SMRNMI
* default open
* when open : mnstatus.nmie init with 1 and allow to write 0
* when close : align mnstatus.nmie behavior with the manual
> fix(format): adjust code format and add NMIE_INIT config

- src/isa/riscv64/difftest/ref.c
CONFIG_MSIZE may be wider than 32-bit.
> fix(ref): use uint64_t for the loop iterator

- include/memory/store_queue_wrapper.h
- src/memory/paddr.c
- src/memory/store_queue_wrapper.cpp
This commit adds the reset function for the store queue. It is called during init_mem.
> fix(store_queue): clear the queue when init_mem

- src/cpu/difftest/ref.c
- src/device/device.c
init_flash should be put in init_device and called only once during multiple difftest runs. At every difftest run, only load_flash_contents should be called.
> fix(device): init_flash should be called only once

- scripts/build.mk
.a libraries cannot be recursively loaded. We extract the .o files before linking them together.
This fixes the staticlib build errors when softfloat is enabled.
> fix(build): extract .a files before running ar

- src/isa/riscv64/instr/fp.c
- src/isa/riscv64/instr/rvc/decode.h
- src/isa/riscv64/instr/vp.c
Including fldst instrucitons under RVC extension.
> fix(fs,vs): fix check fs/vs when executing float/vector instr.

- src/device/flash.c
The flash device is registered when `add_mmio_map` is called with the space pointer. The space pointer is fixed after this registration. However, there is a wrong `new_space` call when `flash_img` is not defined, which updates the flash space pointer. The flash contents are thus incorrectly loaded to the new pointer. However, the IO device table still uses the legacy pointer.
This commits fix it by using the mmap allocator and the fixed flash_base pointer.
> fix(flash): use mmap to create the io space

- src/isa/riscv64/reg.c
Display mnstatus, mncause, mnepc when turn on RISC-V Resumable NonMaskable Interrupts Extension.
> feat: add display csr when turn on RV_SMRNMI.

- src/isa/riscv64/system/trigger.c
`extern Decode *prev_s;` inside a switch case block, which is not allowed because it is a declaration and not an executable statement.
> fix(trigger): extern label should not be inside switch case block.

- src/memory/paddr.c
NEMU should call raise_access_fault directly in paddr_write, rather than raise_read_access_fault.
> fix(exception): fix exception type raised in paddr_write.

- src/isa/riscv64/difftest/dut.c
- src/isa/riscv64/difftest/ref.c
- src/isa/riscv64/local-include/csr.h
- src/isa/riscv64/local-include/intr.h
- src/isa/riscv64/system/priv.c
The previous `csr_read` and `csr_write` functions contained a lot of if-else-if structures, making maintenance difficult.
I have rewritten these two functions using switch-case statements, including:
* For specific CSR, all related operations are placed under the corresponding case, while the typical CSRs are handled using the default case.
* For a series of consecutive CSRs, like pmpaddr, using switch-case was less convenient, so I kept the original if checks.
* Additionally, I removed some always-true code, dead code and the read-write code for some typical CSRs that were occupying a separate case.
> refactor(csrrw): rewrite csr read/write using switch-case instead of multiple if-else.

- scripts/checkpoint_example/rebuild_fw_payload.sh
- scripts/checkpoint_example/repo.list
With this script, it is easy to convert any built fw_payload.bin into a binary file capable of generating checkpoints, which can then be combined with the existing scripts in `scripts/checkpoint_example` to generate checkpoints more easily
> chore: add new script to convert the built fw_payload.bin into a binary capable of generating checkpoint

- src/isa/riscv64/system/mmu.c
The RISC-V Hypervisor extension introduces Sv39x4/Sv48x4 translation scheme, in which the virtual page number (VPN) of the root page table is widened by 2 bits. For Sv39x4, VPN[2] is widened, while for Sv48x4, VPN[3] is widened. This should be handled when NEMU is generating the physical address for G-stage PTEs.
In our earlier implementation of Sv48/Sv48x4 support, we overlooked the handling of the GVPNi function. This oversight led to incorrect PTE address calculations at levels 2 and 3 for Sv48x4. This patch resolves the issue.
> fix(mmu): paddr for root page table entries in Sv48x4

- src/cpu/cpu-exec.c
Perviously, function iqueue_commit is only called in perf_opt exec(). This caused that the record last insts function does not work when PERF_OPT.
> fix(cpu-exec): record last insts when PERF_OPT disabled

- src/isa/riscv64/system/priv.c
The writability of the LCOFI bit in hvip does not depend on the Shlcofideleg extension.
For implementations that support Smcdeleg/Ssccfg, Sscofpmf, Smaia/Ssaia, and the H extension, the LCOFI bit (bit 13) in each of hvip and hvien is implemented and writable.
Extension Shlcofideleg supports delegating LCOFI interrupts to VS-mode. If the Shlcofideleg extension is implemented, hideleg bit 13 is writable; otherwise, it is read-only zero.
> fix(hvip): fix the MASK of HVIP for LCOFI bit.

- include/cpu/difftest.h
- src/memory/paddr.c
In the specification, ` greater than or equal to the width of the promoted left operand, the behavior is undefined.`
In `gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)`, this may work correctly when using O2 optimization, but when using -O0, shifting left past the bit width of the data type will cause a loop.
The mask is involved in the store check, so we need to print the mask out for debugging.
> fix(store_event): Undefined Behavior that shift

- src/isa/riscv64/reg.c
This patch improves the display of registers:
* Reorder the CSRs to follow conventions and improve readability.
* Introduce new macros to enhance the readability and maintainability of the code.
* Add horizontal rules to better distinguish between register sections.
Before:
After:
> feat: improve the display of registers

- src/isa/riscv64/instr/rvv/vcompute.h
* only vmv.xs, vfmv.fs, vcpop.m and vfirst.m not set vs.dirty
> fix(vector): always set vs.dirty when inst may change vector state

- src/isa/riscv64/system/priv.c
This pr fix sdt/sie interaction logic:
For the write behavior of `mstatus/vsstatus.sdt`, since it is directly written, the `sdt` field in `new_val` can be used to determine whether to write `sdt` and affect `sie`. For the write behavior of `sstatus.sdt`, due to changes in the write mask when `DTEclose` is enabled, the original value of `sstatus.sdt` must be considered for its impact on `sie` when `new_val.sdt` cannot be written.
> fix(dbltrp): fix sdt/sie interaction logic

- include/profiling/profiling_control.h
- src/cpu/cpu-exec.c
- src/isa/riscv64/instr/special.h
- src/monitor/monitor.c
- src/profiling/profiling_control.c
Previously, the global instruction counter variable (g_nr_guest_instr) would be reset to 1 when executing nemu_trap 0x101 (start profiling) or receiving ctrl-c signal to start checkpointing, so that profiling and profiling mechanism could create checkpoints in specified intervals.
However, g_nr_guest_instr is a very important variable, which are and will be used in CSRs (minstret, mtime, mcycle) and timer device (clint). It's not good to reset it during running.
This patch modifies the original reset_inst_counters(): it now records current instr count as base with get_abs_instr_count(), and rename the function to start_profiling(). per_bb_profile() is also modified to use the difference between origin count and base as new instr count.
> feat(profiling): record instr count as base

- src/cpu/cpu-exec.c
- src/isa/riscv64/system/intr.c
Tcache of NEMU does not store the privilege mode or mmu mode for ifetch. If privilege mode changes and tcache is not flushed, tcache may return an incorrect basic block.
This won't be a problem before, as software of M/S/U mode always uses different address space. But after introducing hypervisor extension, S and VS mode software, U and VU mode software are likely to use same address space.
Previous PR #133 gave a fix that happens to work. It set_sys_state_flag (SYS_STATE_FLUSH_TCACHE) in raise_intr(). However, this flag won't flush tcache until next priv instruction.
Coincidentally, the first instruction of interrupt/exception handler is usually an csrrw tp, CSR_SCRATCH, tp, which is an priv instruction and is always the same in different OSs. This makes NEMU error free in most …
> fix(cpu-exec): flush tcache when intr/excp happens

- include/rtl/pseudo.h
- src/engine/interpreter/rtl-basic.h
- src/isa/mips32/instr/system.h
rtl_j, rtl_jr and rtl_jrelop are special rtl that could not only change guest's (workload's) execution flow but also affect host's (NEMU's) execution flow. They are defined seperately in PERF_OPT mode (as marcos in cpu-exec.c) and normal mode (as functions in rtl-basic.h). They are restricted to being used only directly within EHelper.
rtl_trap contained some legacy code where `rtl_jr` was used incorrectly. This patch removes that improper usages of rtl_jr. Each call to rtl_trap are reviewed to make sure its functionality remains unaffected. Now, every EHelper that calls rtl_trap also calls rtl_priv_jr afterward. (Although mips32 has already been broken and abandoned, a rtl_priv_jr is added to EHelper of syscall to keep consistency)
> fix(rtl): incorrect usage of rtl_jr in other rtl

- src/engine/interpreter/rtl-basic.h
PR #724 introduced an intrcution counting base for profiling, but at the time, the simpoint_profiling() in normal rtl_j and rtl_jr was not adjusted. This patch addresses that oversight.
> fix(profiling): subtract base from instr count

- include/cpu/cpu.h
- src/cpu/cpu-exec.c
- src/isa/riscv64/instr/priv/system.c
- src/isa/riscv64/system/priv.c
This patch adds support for accuracy minstret, instret, mcycle and cycle CSRs for INST_CNT_BY_BB modes, based on PR #350 and #727. Please refer to comments for technical details.
This patch has passed the countertest in [OpenXiangShan/nexus-am](https://github.com/OpenXiangShan/nexus-am).
> feat: accuracy instret and cycle CSR

- src/memory/vaddr.c
This line of logging is printing too much when we don't want (when MEMLOG disabled).
> fix(mem_log): disable cross-page log by default

- src/isa/riscv64/system/mmu.c
this optimize code layout when not using PGO.
yields around 5% of performance on zen4
> opt(mmu): add some likelyhood mark

- src/isa/riscv64/difftest/ref.c
- src/isa/riscv64/local-include/csr.h
- src/isa/riscv64/reg.c
- src/isa/riscv64/system/intr.c
- src/isa/riscv64/system/priv.c
For bits of mideleg that are zero, the corresponding bits in hideleg, hip, and hie are read-only zeros.
The VSSIP, VSTIP, VSEIP in mideleg are read-only ones when the H extension is implemented.
When the hypervisor extension is implemented, if a bit is zero in the same position in both mideleg
and mvien, then that bit is read-only zero in hideleg (in addition to being read-only zero in sip, sie,
hip, and hie). But if a bit for one of interrupts 13-63 is a one in either mideleg or mvien, then the same
bit in hideleg may be writable or may be read-only zero, depending on the implementation. No bits in
hideleg are ever read-only ones. The RISC-V Privileged Architecture further constrains bits 12:0 of
hideleg.
> fix(hideleg): fix the read value of the LCOFI bit of hideleg.

- src/isa/riscv64/system/mmu.c
common case is MODE_U, non-H and no pmm.
this improves around 10% of speed on zen4.
Correctness needs a careful review.
> opt(mmu): add an early out fast path

- Makefile
- scripts/LibcheckpointAlpha.mk
- scripts/build.mk
- scripts/config.mk
- scripts/repos.mk
- scripts/softfloat.mk
Simply migrate the other repo's build process to a separate makefile, and will continue to be refact to make it easier to understand.
The goal is to:
make it easier to handle builds and dependencies when there are more repositories, e.g. the Libcheckpoint repo and the nanopb repo will be added soon.
> refactor(Makefile): Migrate builds from other repos to separate makefiles

- include/cpu/difftest.h
- src/cpu/difftest/dut.c
- src/isa/riscv64/difftest/dut.c
this patch add two api to copy pmp and pmp cfg registers to spike when execute `difftest_attach`, but spike still have many non-register states not sync totally, so this patch just reduce size of the problem, not fix it
> try-fix(difftest attach): Add 'pmp' and 'pmp_cpy' API to difftest_attach, but functionality remains incomplete

- src/memory/vaddr.c
In previous design, before we do `rvh_hlvx_check`, we will only determine whether it is a instruction fetch request (`MEM_TYPE_IFETCH`). If it is a instruction fetch request, there is no need to determine if it is hlvx. However, for the case of examine memory (using `vaddr_read_safe`), the memory type is `MEM_TYPE_READ`, but there is still no need to determine if it is hlvx.
Since both instruction fetch requests and `vaddr_read_safe` function will pass a NULL pointer `s` here, we will decide whether to execute `rvh_hlvx_check` by determining whether or not `s` is NULL.
> fix(vaddr): vaddr_read_safe should not check hlvx instruction

- src/isa/riscv64/system/priv.c
Before this, we assumed that all possible exceptions during CSR read and write operations should be handled according to their priority.
Therefore, we used `has_vi` to record whether a virtual instruction exception exists and ensured that all illegal instruction exceptions take precedence over virtual instruction exceptions.
However, with the implementation of certain extensions like Smcsrind and Smstateen, we encounter scenarios where virtual instruction exceptions must take precedence over illegal instruction exceptions triggered.
For instance, when mstateen0.csrind is set to 1 and hstateen0.csrind is 0, a virtual instruction exception should be raised if VS mode attempts to access sireg. However, if the vsiselect value is reserved in this situation, an illegal instruction exception …
> fix(csr, exception): divide the excep raised from csrrw into 2 stages

- include/checkpoint/serializer.h
- src/checkpoint/serializer.cpp
- src/monitor/monitor.c
This commit introduces the `--using-flash-store-checkpoint` option, which is intended to enable saving checkpoints directly to flash storage.
Currently, this option is not yet implemented in the workflow. Future updates will integrate this feature into the relevant checkpoint handling logic.
> feat: add --store-cpt-in-flash option

- include/checkpoint/serializer.h
- src/checkpoint/serializer.cpp
Replaced the hardcoded `get_pmem` with `serialize_base_addr` to enable specifying the checkpoint storage location via the `--using-flash-store-checkpoint` option. While this change lays the groundwork for saving checkpoints to flash, the functionality is not yet fully implemented and will be completed in future updates.
> feat: replace fixed get_pmem with serialize_base_addr for checkpoint storage

- src/checkpoint/serializer.cpp
Implemented use the `--store-cpt-in-flash` option configure `serialize_reg_base_addr` to point to the flash address.
> feat: support `--store-cpt-in-flash` option to set `serialize_reg_base_addr` to flash address

- include/isa.h
- src/cpu/difftest/ref.c
- src/isa/riscv64/difftest/ref.c
- src/isa/riscv64/include/isa-def.h
- src/isa/riscv64/system/priv.c
Along the same lines, when hstatus.VGEIN is not the number of an implemented guest external interrupt, attempts from M-mode or HS-mode to access CSR vstopei raise an illegal instruction exception, and attempts from VS-mode to access stopei raise a virtual instruction exception.
> fix(aia, exception): Add the missing AIA-related permission checks.

- include/isa.h
- src/cpu/difftest/ref.c
- src/isa/riscv64/difftest/ref.c
- src/isa/riscv64/include/isa-def.h
- src/isa/riscv64/local-include/aia.h
- src/isa/riscv64/system/aia.c
- src/isa/riscv64/system/priv.c
* The current external interrupts come from two sources, `CLINT` and `IMSIC`.
The external interrupt priority number of CLINT is `0`, and the external interrupt priority number of IMSIC is `1~2047`.
We use the global variable `external_interrupt_select` to determine the source of the external interrupt.
If the external interrupt comes from CLINT, `external_interrupt_select` = false;
if the external interrupt comes from IMSIC, `external_interrupt_select` = true.
* The case where the priority number is greater than `255` is added to the interrupt priority comparison method.
* The priority number of each interrupt in the `iprios array` occupies `8` bits, and its read data is masked by the corresponding bit of the `xie` register, so when writing the `xie` register, the `read data` of the …
> fix(aia): external interrupt priority from CLINT or IMSIC

- src/isa/riscv64/system/priv.c
We should know that `MUXDEF` can only be used when the condition is `bool`.
The reason for this is as follows:
> #define CHOOSE2nd(a, b, ...) b
> #define MUX_WITH_COMMA(contain_comma, a, b) CHOOSE2nd(contain_comma a, b)
> #define MUX_MACRO_PROPERTY(p, macro, a, b) MUX_WITH_COMMA(concat(p, macro), a, b)
> // define placeholders for some property
> #define __P_DEF_0  X,
> #define __P_DEF_1  X,
> #define __P_ONE_1  X,
> #define __P_ZERO_0 X,
> // define some selection functions based on the properties of BOOLEAN macro
> #define MUXDEF(macro, X, Y)  MUX_MACRO_PROPERTY(__P_DEF_, macro, X, Y)
> #define MUXNDEF(macro, X, Y) MUX_MACRO_PROPERTY(__P_DEF_, macro, Y, X)
> #define MUXONE(macro, X, Y)  MUX_MACRO_PROPERTY(__P_ONE_, macro, X, Y)
> #define MUXZERO(macro, X, Y) …
> fix(hgeie): fix macro generation logic for 'HGEIE_MASK'

- scripts/generate_so_for_difftest.sh
`riscv64-xs-ref_defconfig` is currently not being generated properly, so here need `make clean-all`.
> chore: fix so generation

- src/isa/riscv64/instr/rvv/vcompute_impl.c
* When executing vfred related instructions, we need to check that mstatus.fs and vsstatus.fs are not off. If they are off, an illegal instruction exception will be reported. NEMU missed this check.
* This patch fixes it.
> fix(vfred): execute vfred inst need mstatus.fs and vsstatus.fs not off

- src/isa/riscv64/local-include/intr.h
- src/isa/riscv64/system/priv.c
* if hvictl.VTI = 0:
* the highest-priority pending-and-enabled major interrupt indicated
* by vsip and vsie other than a supervisor external interrupt(code 9),
* using the priority numbers assigned by hviprio1 and hviprio2. 
* 
* A hypervisor can choose to employ registers hviprio1 and hviprio2
* when emulating the (virtual) supervisor-level iprio array accessed
* indirectly through siselect and sireg (really vsiselect and vsireg)
* for a virtual hart. For interrupts not in the subset supported by
* hviprio1 and hviprio2, the priority number bytes in the emulated
* iprio array can be read-only zeros.
> fix(vstopi): remove SEI from Candidate 4

- src/isa/riscv64/system/trigger.c
CPU XiangShan only support trigger for address, which means that select bit in mcontrol6 is read-only zero.
> fix(tdata1): fix the select bit in mcontrol6

- src/isa/riscv64/local-include/aia.h
- src/isa/riscv64/system/aia.c
- src/isa/riscv64/system/priv.c
* For `mtopi` / `stopi` :
> AIA Spec:
> If all bytes of the supervisor-level iprio array are read-only zeros, a simplified implementation of field `IPRIO` is allowed in which its value is always `1` whenever `stopi` is not zero.
* We are configurable and `do not need` to simplify the implementation.
* For `vstopi`: 
> AIA Spec:
> Ties in nominal priority are broken as usual by the default priority order from `Table 8`, unless `hvictl` fields `VTI = 1` and `IID ≠ 9` (last item in the candidate list above), in which case default priority order is determined solely by `hvictl.DPR`.
> If bit `IPRIOM` (IPRIO Mode) of `hvictl` is zero, `IPRIO` in `vstopi` is 1; else, if the priority number for the highest-priority candidate is within the range `1` to `255`, `IPRIO` is that value; else, `IPRIO` …
> fix(xtopi): fix xtopi generation conditions

- src/isa/riscv64/system/priv.c
* xstateen.IMSIC should control to access sireg/vsireg when siselect/vsiselect is between 0x70 and 0xff.
* xstateen.AIA should control to access sireg when siselect is between 0x30 and 0x3f.
> fix(Smstateen): fix access to sireg/vsireg

- src/isa/riscv64/local-include/intr.h
- src/isa/riscv64/system/priv.c
For implementations that support Smcdeleg, Sscofpmf, and Smaia, the local counter overflow interrupt (LCOFI) bit (bit 13) in each of CSRs mvip and mvien is implemented and writable.
For implementations that support Smcdeleg/Ssccfg, Sscofpmf, Smaia/Ssaia, and the H extension, the LCOFI bit (bit 13) in each of hvip and hvien is implemented and writable.
> fix(LCOFI): fix writable of LCOFI bit(13) of mvip/mvien/hvip/hvien

- src/isa/riscv64/local-include/trigger.h
This PR fixes linking errors that occur when compiling NEMU with -O0 optimization level. The issue was caused by inline functions in `trigger.h` that were not marked as `static`, leading to multiple definition errors during linking.
- Added `static` keyword to the following inline functions in `trigger.h`:
- `get_tdata1`
- `get_tdata2`
- `get_tdata3`
When compiling with -O0, the compiler does not perform inline optimization, which means it generates actual function calls instead of inlining the function body. Without the `static` keyword, each compilation unit that includes `trigger.h` would generate its own copy of these functions, leading to multiple definition errors during linking.
Adding the `static` keyword ensures that:
1. Each compilation unit gets its own copy of these functions …
> fix: add static keyword to inline functions in trigger.h

- src/cpu/difftest/ref.c
- src/isa/riscv64/include/isa-def.h
- src/isa/riscv64/init.c
- src/isa/riscv64/system/priv.c
> AIA spec:
> A write to a *topei CSR claims the reported interrupt identity by clearing its pending bit in the interrupt file. The value written is ignored; rather, the current readable value of the register determines which interrupt-pending bit is cleared. Specifically, when a *topei CSR is written, if the register value has interrupt identity in bits 26:16, then the interrupt file’s pending bit for interrupt is cleared. When a *topei CSR’s value is zero, a write to the register has no effect.
> If a read and write of a *topei CSR are done together by a single CSR instruction (CSRRW, CSRRS, or CSRRC), the value returned by the read indicates the pending bit that is cleared.
* There is a situation where the instruction is csrrw a5, 0x15c, 0, where 0x15c is the stopei register.
* The …
> fix(aia, difftest): fix AIA sync between XiangShan and NEMU

- src/isa/riscv64/system/mmu.c
Currently, we no longer need to perform address misalign checks here, as the current checks for address misalign  are very fragmented.
This is because we do support hardware misalign  in most cases, but not in a few, so we have added separate checks for non-aligned accesses elsewhere.
> fix(mmu): remove address misalign check from isa_mmu_check

- src/isa/riscv64/system/mmu.c
According to the RISC-V specification, for PMP (Physical Memory Protection) checks, if an address does not match any PMP entry, the processor must then check the current privilege mode. If the current mode is Machine mode (Mode M), no exception is raised; otherwise, an access fault must be reported.
In contrast, for PMA (Physical Memory Attributes) checks, they are always enforced, even in Machine mode. If an address does not match any PMA entry, an access fault must be reported.
> fix(PMA): accessFault should be reported when none PMA entry matches

- README.md
I am Yang Guolin from the RACE team,I'm testing RVV for fp16 to int8 conversion,I have noticed that Vector and Hypervisor extensions were merged into XiangShan master, riscv64-xs_defconfig (and other riscv64-xs defconfigs) has enabled RVH and RVV,therefore, keeping riscv64-rvv-ref_defconfig in README will cause misunderstanding to users.
> fix(README): Delete unnecessary config related tables

- src/isa/riscv64/system/mmu.c
According to Smrnmi Extension, When NMIE=0, the hart behaves as though mstatus.MPRV were clear, regardless of the current setting of mstatus.MPRV. The previous code does not check NMIE wherever MPRV is used, which causes some problems. This patch adds a function to get the proper MPRV.
> fix(mmu): MPRV should be treated as clear when NMIE = 0

- src/isa/riscv64/include/isa-def.h
- src/isa/riscv64/system/priv.c
* This PR fix csr write/read hideleg and csr read sie in V mode.
* `hideleg->val` is to diff `RTL` and `NEMU` and `hideleg_reg` is register value. The rdata of the `hideleg` register is `reg & mideleg & HIDELEG_MASK |  reg & mvien & LCI` in XiangShan.
* A situation may arise at this point. First, write `1` to bit `13` of `hideleg`. At this point, `hideleg.reg.LCOFIP` = `1` in the RTL. Since bit `13` of `mideleg` or `mvien` is `0`, the RTL's `hideleg.rdata` is `0`. The NEMU's `get_hideleg` is also `0`, and a diff is performed with the RTL. Then, write `1` to bit `13` of `mideleg`. The RTL's `hideleg.rdata` becomes `1`, but the NEMU's `hideleg->val` is the result of `csr_writeback` and `csr_prepare` operations, which is the value of `get_hideleg`, which is `0`. This causes an error in the …
> fix(csr): fix csr write and read register to pass hyp test
